build:
  version: 1.0.0
customers:
  message: "Welcome to EazyBank accounts related local APIs"
  contactDetails:
    name: "Jhon Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    -(555) 555-1234
    -(555) 523-1345
