build:
  version: 1.0.0
users:
  message: "Welcome to EazyBank users related QA APIs"
  contactDetails:
    name: "Jhon Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    -(888) 666-1234
    -(888) 623-1345